# Generated by Django 4.2.2 on 2023-06-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_phone', '0003_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
