# Generated by Django 4.2.2 on 2023-07-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_phone', '0005_chat_delete_spam_user_dob_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default='2000/5/01'),
        ),
    ]
