# Generated by Django 4.2.2 on 2023-07-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_phone', '0006_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default='2000-05-01'),
        ),
    ]
