# Generated by Django 4.2.2 on 2023-07-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_phone', '0007_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
